base([
event('Myelodysplastic Syndromes',association,'CD4'),
event('IFNG',association,'CD8A'),
event('Colorectal Neoplasms',association,'IL2'),
event('Colorectal Neoplasms',association,'CD8A'),
event('NEOPLASMS',association,'CD8A'),
event('NEOPLASMS',association,'HLA-A'),
event('Colorectal Neoplasms',association,'CD4'),
event('HLA-A',association,'IL2'),
event('NEOPLASMS',association,'CD4'),
event('IFNG',positive_correlation,'HLA-C'),
event('HLA-C',positive_correlation,'IFNG'),
event('HLA-A',association,'CD8A'),
event('IFNG',association,'CD4'),
event('INFECTIONS',association,'PMEL'),
event('MELANOMA',association,'PMEL'),
event('HIV Infections',association,'CD8A'),
event('CD8A',association,'CD28'),
event('IL2',negative_correlation,'Cytomegalovirus Infections'),
event('Cytomegalovirus Infections',negative_correlation,'IL2'),
event('Virus Diseases',association,'CD8A'),
event('IL2',association,'CD28'),
event('HIV Infections',association,'CD28'),
event('HIV Infections',association,'IL2'),
event('Virus Diseases',association,'CD4'),
event('Cytomegalovirus Infections',association,'CD28'),
event('IL2',association,'CD8A'),
event('MELANOMA',association,'TYR'),
event('MELANOMA',association,'MLANA'),
event('MELANOMA',association,'CD34'),
event('MELANOMA',association,'MAGEA3'),
event('NEOPLASMS',association,'MLANA'),
event('Autistic Disorder',association,'WDR11'),
event('Autistic Disorder',association,'CD4'),
event('WDR11',association,'CD4'),
event('IFNG',positive_correlation,'ICAM1'),
event('ICAM1',positive_correlation,'IFNG'),
event('ALOPECIA',association,'CD8A'),
event('CTAG1A',association,'CD4'),
event('NEUROBLASTOMA',association,'CD4'),
event('CTAG1A',association,'CD8A'),
event('NEUROBLASTOMA',association,'CD8A'),
event('NEUROBLASTOMA',association,'CTAG1A'),
event('MYO1G',association,'CD8A'),
event('Granulomatosis with Polyangiitis',association,'CD4'),
event('Granulomatosis with Polyangiitis',association,'TNF'),
event('Granulomatosis with Polyangiitis',association,'CD8A'),
event('Granulomatosis with Polyangiitis',association,'PRTN3'),
event('HLA-A',association,'UBE2V1'),
event('NEOPLASMS',association,'UBE2V1'),
event('HLA-DRB1',association,'UBE2V1'),
event('UBE2V1',association,'CD4'),
event('Lung Neoplasms',association,'TMEM189'),
event('Lung Neoplasms',association,'UBE2V1'),
event('Colorectal Neoplasms',association,'HLA-C'),
event('Colorectal Neoplasms',association,'NCAM1'),
event('NEOPLASMS',association,'NCAM1'),
event('Colorectal Neoplasms',association,'HLA-B'),
event('Colorectal Neoplasms',association,'B3GAT1'),
event('NEOPLASMS',association,'B3GAT1'),
event('Chemical and Drug Induced Liver Injury',association,'CD8A'),
event('CD28',negative_correlation,'Hepatitis C'),
event('Hepatitis C',negative_correlation,'CD28'),
event('CD40LG',negative_correlation,'Hepatitis C'),
event('Hepatitis C',negative_correlation,'CD40LG'),
event('CD80',negative_correlation,'Hepatitis C'),
event('Hepatitis C',negative_correlation,'CD80'),
event('CD8A',negative_correlation,'Hepatitis C'),
event('Hepatitis C',negative_correlation,'CD8A'),
event('Chemical and Drug Induced Liver Injury',association,'CD28'),
event('Liver Diseases',association,'CD28'),
event('Hepatitis C Chronic',association,'CD28'),
event('Liver Diseases',association,'CD8A'),
event('Leukemia Myelogenous Chronic BCR-ABL Positive',association,'HLA-A'),
event('Leukemia Myeloid',association,'ELANE'),
event('Leukemia Myeloid',association,'PRTN3'),
event('LEUKEMIA',association,'CD4'),
event('CD8A',positive_correlation,'ELANE'),
event('ELANE',positive_correlation,'CD8A'),
event('LEUKEMIA',association,'CD8A'),
event('IFNG',positive_correlation,'ELANE'),
event('ELANE',positive_correlation,'IFNG'),
event('ELANE',association,'CD4'),
event('LEUKEMIA',association,'ELANE'),
event('CHROMIUM-51',association,'CD8A'),
event('CD8A',positive_correlation,'MLANA'),
event('MLANA',positive_correlation,'CD8A'),
event('CTAG1A',positive_correlation,'ISCOMATRIX'),
event('ISCOMATRIX',positive_correlation,'CTAG1A'),
event('NEOPLASMS',negative_correlation,'ISCOMATRIX'),
event('ISCOMATRIX',negative_correlation,'NEOPLASMS'),
event('CTAG1A',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'CTAG1A'),
event('NEOPLASMS',association,'CTAG1A'),
event('IGHV1-9',positive_correlation,'CTAG1A'),
event('CTAG1A',positive_correlation,'IGHV1-9'),
event('CD8A',positive_correlation,'ISCOMATRIX'),
event('ISCOMATRIX',positive_correlation,'CD8A'),
event('INFECTIONS',association,'HLA-A'),
event('INFECTIONS',association,'HLA-B'),
event('HIV Infections',association,'HLA-C'),
event('Heredodegenerative Disorders Nervous System',association,'CD4'),
event('Heredodegenerative Disorders Nervous System',association,'CD8A'),
event('Paraparesis Tropical Spastic',association,'HLA-A'),
event('Paraparesis Tropical Spastic',association,'CD8A'),
event('Heredodegenerative Disorders Nervous System',association,'HLA-A'),
event('Heredodegenerative Disorders Nervous System',association,'IL2RA'),
event('IL2RA',association,'CD8A'),
event('NEOPLASMS',association,'ERBB2'),
event('ERBB2',association,'SLTM'),
event('Neoplasm Metastasis',association,'ERBB2'),
event('Cytomegalovirus Infections',association,'CD8A'),
event('Cytomegalovirus Infections',association,'HLA-C'),
event('Cytomegalovirus Infections',association,'IFNG'),
event('HEMOCHROMATOSIS',association,'P.C282Y'),
event('HEMOCHROMATOSIS',association,'P.H63D'),
event('HLA-C',association,'CD8A'),
event('HEMOCHROMATOSIS',association,'HFE'),
event('Carcinoma Renal Cell',association,'CD8A'),
event('Intestinal Pseudo-Obstruction',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'Intestinal Pseudo-Obstruction'),
event('STRONGYLOIDIASIS',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'STRONGYLOIDIASIS'),
event('Malabsorption Syndromes',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'Malabsorption Syndromes'),
event('SCABIES',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'SCABIES'),
event('Elephantiasis Filarial',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'Elephantiasis Filarial'),
event('MALARIA',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'MALARIA'),
event('ONCHOCERCIASIS',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'ONCHOCERCIASIS'),
event('Neglected Diseases',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'Neglected Diseases'),
event('Fecal Incontinence',negative_correlation,'IVERMECTIN'),
event('IVERMECTIN',negative_correlation,'Fecal Incontinence'),
event('COVID-19',negative_correlation,'CHLOROQUINE'),
event('CHLOROQUINE',negative_correlation,'COVID-19'),
event('COVID-19',negative_correlation,'REMDESIVIR'),
event('REMDESIVIR',negative_correlation,'COVID-19'),
event('Coronavirus Infections',association,'SPECC1'),
event('Coronavirus Infections',negative_correlation,'REMDESIVIR'),
event('REMDESIVIR',negative_correlation,'Coronavirus Infections'),
event('Coronaviridae Infections',negative_correlation,'IDX184'),
event('IDX184',negative_correlation,'Coronaviridae Infections'),
event('SOFOSBUVIR',association,'RNA Virus Infections'),
event('RIBAVIRIN',association,'RNA Virus Infections'),
event('Virus Diseases',negative_correlation,'SOFOSBUVIR'),
event('SOFOSBUVIR',negative_correlation,'Virus Diseases'),
event('Virus Diseases',negative_correlation,'IDX184'),
event('IDX184',negative_correlation,'Virus Diseases'),
event('Virus Diseases',negative_correlation,'RIBAVIRIN'),
event('RIBAVIRIN',negative_correlation,'Virus Diseases'),
event('DEATH',negative_correlation,'IDX184'),
event('IDX184',negative_correlation,'DEATH'),
event('Coronaviridae Infections',negative_correlation,'SOFOSBUVIR'),
event('SOFOSBUVIR',negative_correlation,'Coronaviridae Infections'),
event('Coronaviridae Infections',negative_correlation,'RIBAVIRIN'),
event('RIBAVIRIN',negative_correlation,'Coronaviridae Infections'),
event('COVID-19',negative_correlation,'FAVIPIRAVIR'),
event('FAVIPIRAVIR',negative_correlation,'COVID-19'),
event('COVID-19',negative_correlation,'UMIFENOVIR'),
event('UMIFENOVIR',negative_correlation,'COVID-19'),
event('Liver Cirrhosis Biliary',association,'CD4'),
event('Liver Cirrhosis Biliary',association,'DLAT'),
event('Liver Cirrhosis Biliary',association,'CD8A'),
event('DLAT',association,'CD8A'),
event('Carcinoma Renal Cell',association,'MUC1'),
event('MALARIA',association,'CS'),
event('SCHIZOPHRENIA',association,'CD8A'),
event('CD4',positive_correlation,'Mental Disorders'),
event('Mental Disorders',positive_correlation,'CD4'),
event('SCHIZOPHRENIA',association,'CD4'),
event('CALCIUM',association,'FCGR3A'),
event('HLA-C',bind,'CD8A'),
event('HLA-C',association,'CD4'),
event('TRBV20OR9-2',bind,'CD8A'),
event('HSPA8',association,'CD4'),
event('MELANOMA',association,'HSPA8'),
event('MELANOMA',association,'CD4'),
event('Stomach Neoplasms',association,'CD4'),
event('Stomach Neoplasms',association,'CD8A'),
event('Stomach Neoplasms',association,'HLA-B'),
event('Stomach Neoplasms',association,'HLA-A'),
event('HLA-G',association,'CD4'),
event('Stomach Neoplasms',association,'HLA-G'),
event('Stomach Neoplasms',association,'HLA-C'),
event('HLA-G',association,'CD8A'),
event('TLR3',positive_correlation,'CYMD'),
event('CYMD',positive_correlation,'TLR3'),
event('IL10',positive_correlation,'IMIQUIMOD'),
event('IMIQUIMOD',positive_correlation,'IL10'),
event('IL12B',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'IL12B'),
event('TLR4',positive_correlation,'CYMD'),
event('CYMD',positive_correlation,'TLR4'),
event('CD83',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'CD83'),
event('TLR9',positive_correlation,'CPG-OLIGONUCLEOTIDE'),
event('CPG-OLIGONUCLEOTIDE',positive_correlation,'TLR9'),
event('IL10',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'IL10'),
event('CD86',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'CD86'),
event('TLR3',positive_correlation,'Poly I-C'),
event('Poly I-C',positive_correlation,'TLR3'),
event('TLR7',positive_correlation,'IMIQUIMOD'),
event('IMIQUIMOD',positive_correlation,'TLR7'),
event('CD40',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'CD40'),
event('CD80',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'CD80'),
event('Colorectal Neoplasms',negative_correlation,'INDOMETHACIN'),
event('INDOMETHACIN',negative_correlation,'Colorectal Neoplasms'),
event('PROSTAGLANDINS',association,'Colorectal Neoplasms'),
event('PROSTAGLANDINS',association,'NEOPLASMS'),
event('IL10',negative_correlation,'INDOMETHACIN'),
event('INDOMETHACIN',negative_correlation,'IL10'),
event('FOXP3',negative_correlation,'INDOMETHACIN'),
event('INDOMETHACIN',negative_correlation,'FOXP3'),
event('NEOPLASMS',association,'IL10'),
event('NEOPLASMS',negative_correlation,'INDOMETHACIN'),
event('INDOMETHACIN',negative_correlation,'NEOPLASMS'),
event('Colorectal Neoplasms',negative_correlation,'CELECOXIB'),
event('CELECOXIB',negative_correlation,'Colorectal Neoplasms'),
event('CTAG1A',association,'CD8B'),
event('Ovarian Neoplasms',association,'CTAG1A'),
event('CTAG1A',association,'TRBV20OR9-2'),
event('NEOPLASMS',association,'TRBV20OR9-2'),
event('TRBV20OR9-2',association,'CD4'),
event('TRBV20OR9-2',association,'CD8A'),
event('Ovarian Neoplasms',association,'TRBV20OR9-2'),
event('Graft vs Host Disease',association,'HLA-DRB3'),
event('Graft vs Host Disease',association,'CD4'),
event('Graft vs Host Disease',association,'HLA-A'),
event('Graft vs Host Disease',association,'HLA-DPB1'),
event('CD4',bind,'CD8A'),
event('N(EPSILON)-PALMITOYLLYSINE',bind,'TLR2'),
event('N(EPSILON)-PALMITOYLLYSINE',bind,'CD4'),
event('LIPOPEPTIDES',association,'CD4'),
event('TLR2',association,'CD8A'),
event('CD4',positive_correlation,'CLIP1'),
event('CLIP1',positive_correlation,'CD4'),
event('NXF1',association,'CLIP1'),
event('NEOPLASMS',association,'KRT20'),
event('NEOPLASMS',association,'CLIP1'),
event('CD8A',positive_correlation,'CLIP1'),
event('CLIP1',positive_correlation,'CD8A'),
event('HLA-B',association,'CD8A'),
event('TUBERCULOSIS',association,'HLA-C'),
event('CD28',positive_correlation,'CD4'),
event('CD4',positive_correlation,'CD28'),
event('MELANOMA',association,'HLA-B'),
event('MELANOMA',association,'CD8A'),
event('Arthritis Psoriatic',association,'IL17A'),
event('INFLAMMATION',association,'CD4'),
event('SPONDYLARTHRITIS',association,'HLA-B'),
event('ARTHRITIS',association,'HLA-B'),
event('COLITIS',association,'HLA-B'),
event('CD4',association,'IL17A'),
event('CD4',positive_correlation,'TNF'),
event('TNF',positive_correlation,'CD4'),
event('HIV Infections',association,'KIR3DL1'),
event('KIR3DL1',association,'CD8A'),
event('CD8A',negative_correlation,'HLA-G'),
event('HLA-G',negative_correlation,'CD8A'),
event('RS3869068',association,'HIV Infections'),
event('RS2395029',negative_correlation,'HIV Infections'),
event('HIV Infections',negative_correlation,'RS2395029'),
event('RS9264942',negative_correlation,'HIV Infections'),
event('HIV Infections',negative_correlation,'RS9264942'),
event('HIV Infections',association,'ZNRD1'),
event('HIV Infections',association,'HCP5'),
event('HIV Infections',association,'RS3869068'),
event('Adenocarcinoma Follicular',negative_correlation,'METHIMAZOLE'),
event('METHIMAZOLE',negative_correlation,'Adenocarcinoma Follicular'),
event('HYPERTHYROIDISM',positive_correlation,'TRIIODOTHYRONINE'),
event('TRIIODOTHYRONINE',positive_correlation,'HYPERTHYROIDISM'),
event('HYPERTHYROIDISM',positive_correlation,'THYROXINE'),
event('THYROXINE',positive_correlation,'HYPERTHYROIDISM'),
event('HYPERTHYROIDISM',negative_correlation,'METHIMAZOLE'),
event('METHIMAZOLE',negative_correlation,'HYPERTHYROIDISM'),
event('Adenocarcinoma Follicular',association,'KRT20'),
event('Adenocarcinoma Follicular',negative_correlation,'PREDNISOLONE'),
event('PREDNISOLONE',negative_correlation,'Adenocarcinoma Follicular'),
event('TPO',negative_correlation,'PREDNISOLONE'),
event('PREDNISOLONE',negative_correlation,'TPO'),
event('Paralyses Familial Periodic',negative_correlation,'METHIMAZOLE'),
event('METHIMAZOLE',negative_correlation,'Paralyses Familial Periodic'),
event('Paralyses Familial Periodic',negative_correlation,'PREDNISOLONE'),
event('PREDNISOLONE',negative_correlation,'Paralyses Familial Periodic'),
event('HYPERTHYROIDISM',negative_correlation,'PREDNISOLONE'),
event('PREDNISOLONE',negative_correlation,'HYPERTHYROIDISM'),
event('Alopecia Areata',association,'KLRK1'),
event('CD4',positive_correlation,'Alopecia Areata'),
event('Alopecia Areata',positive_correlation,'CD4'),
event('Alopecia Areata',association,'CD8A'),
event('MYOSITIS',association,'IFIH1'),
event('MYOSITIS',association,'MGA'),
event('MYOSITIS',association,'MORC3'),
event('INFLAMMATION',association,'IFIH1'),
event('Myotonic Dystrophy',association,'MORC3'),
event('TRIM33',positive_correlation,'ATROPHY'),
event('ATROPHY',positive_correlation,'TRIM33'),
event('Myotonic Dystrophy',association,'TRIM33'),
event('MORC3',positive_correlation,'ATROPHY'),
event('ATROPHY',positive_correlation,'MORC3'),
event('Leukemic Infiltration',association,'MORC3'),
event('Postoperative Complications',association,'CD4'),
event('Encephalomyelitis Autoimmune Experimental',association,'MS4A1'),
event('Leishmaniasis Cutaneous',association,'CD4'),
event('Leishmaniasis Cutaneous',association,'TGFB1'),
event('Leishmaniasis Cutaneous',association,'IL17A'),
event('Leishmaniasis Cutaneous',association,'IL23A'),
event('IL17A',association,'CD4'),
event('Leishmaniasis Cutaneous',association,'IL6'),
event('NEOPLASMS',association,'PDCD1'),
event('ID3',positive_correlation,'Lupus Erythematosus Systemic'),
event('Lupus Erythematosus Systemic',positive_correlation,'ID3'),
event('Encephalomyelitis Autoimmune Experimental',association,'CD4'),
event('FOXP3',positive_correlation,'ID3'),
event('ID3',positive_correlation,'FOXP3'),
event('ID1',negative_correlation,'Encephalomyelitis Autoimmune Experimental'),
event('Encephalomyelitis Autoimmune Experimental',negative_correlation,'ID1'),
event('Familial antiphospholipid syndrome',association,'ID3'),
event('ID3',positive_correlation,'IKZF2'),
event('IKZF2',positive_correlation,'ID3'),
event('CD4',positive_correlation,'ID3'),
event('ID3',positive_correlation,'CD4'),
event('Lymphoma B-Cell',association,'CD19'),
event('IL12A',association,'CD19'),
event('EBI3',positive_correlation,'SARCOIDOSIS'),
event('SARCOIDOSIS',positive_correlation,'EBI3'),
event('IL12A',positive_correlation,'SARCOIDOSIS'),
event('SARCOIDOSIS',positive_correlation,'IL12A'),
event('SARCOIDOSIS',association,'CD19'),
event('Dog Diseases',negative_correlation,'MILTEFOSINE'),
event('MILTEFOSINE',negative_correlation,'Dog Diseases'),
event('Dog Diseases',association,'CD4'),
event('Dog Diseases',association,'FOXP3'),
event('Dog Diseases',negative_correlation,'ALLOPURINOL'),
event('ALLOPURINOL',negative_correlation,'Dog Diseases'),
event('Dog Diseases',negative_correlation,'Meglumine Antimoniate'),
event('Meglumine Antimoniate',negative_correlation,'Dog Diseases'),
event('Dog Diseases',association,'IL2RA'),
event('P.Q309R',positive_correlation,'HIV Infections'),
event('HIV Infections',positive_correlation,'P.Q309R'),
event('P.Q309R',positive_correlation,'RIBAVIRIN'),
event('RIBAVIRIN',positive_correlation,'P.Q309R'),
event('Hepatitis C',negative_correlation,'RIBAVIRIN'),
event('RIBAVIRIN',negative_correlation,'Hepatitis C'),
event('Hepatitis C',association,'P.Q309R'),
event('HIV Infections',association,'CD4'),
event('Hepatitis C',association,'CD4'),
event('Signs and Symptoms',positive_correlation,'TENOFOVIR'),
event('TENOFOVIR',positive_correlation,'Signs and Symptoms'),
event('MYCOSES',association,'CD4'),
event('MYCOSES',association,'TNFRSF9'),
event('Invasive Fungal Infections',association,'HLA-A'),
event('CSF2',association,'CD4'),
event('MYCOSES',association,'HLA-DRB1'),
event('MYCOSES',association,'HLA-A'),
event('Arthritis Psoriatic',association,'CD4'),
event('Graft vs Host Disease',association,'CD8A'),
event('IL23R',association,'CD8A'),
event('Graft vs Host Disease',association,'RARA'),
event('Graft vs Host Disease',positive_correlation,'TRETINOIN'),
event('TRETINOIN',positive_correlation,'Graft vs Host Disease'),
event('CD8A',positive_correlation,'TRETINOIN'),
event('TRETINOIN',positive_correlation,'CD8A'),
event('IL37',association,'CD8A'),
event('Graft vs Host Disease',association,'IL37'),
event('RARA',positive_correlation,'TRETINOIN'),
event('TRETINOIN',positive_correlation,'RARA'),
event('TRETINOIN',association,'IL37'),
event('CD4',negative_correlation,'IL37'),
event('IL37',negative_correlation,'CD4'),
event('TBX21',association,'CD8A'),
event('PRMT5',association,'CD8A'),
event('Precancerous Conditions',association,'PRMT5'),
event('PRMT5',association,'CD4'),
event('Carotid Stenosis',association,'TNF'),
event('Carotid Stenosis',association,'CCL2'),
event('IL4',positive_correlation,'TRAMETINIB'),
event('TRAMETINIB',positive_correlation,'IL4'),
event('MDK',negative_correlation,'TRAMETINIB'),
event('TRAMETINIB',negative_correlation,'MDK'),
event('IL2',negative_correlation,'TRAMETINIB'),
event('TRAMETINIB',negative_correlation,'IL2'),
event('TNF',negative_correlation,'TRAMETINIB'),
event('TRAMETINIB',negative_correlation,'TNF'),
event('IL10',positive_correlation,'TRAMETINIB'),
event('TRAMETINIB',positive_correlation,'IL10'),
event('INFLAMMATION',positive_correlation,'TRAMETINIB'),
event('TRAMETINIB',positive_correlation,'INFLAMMATION'),
event('IFNG',negative_correlation,'TRAMETINIB'),
event('TRAMETINIB',negative_correlation,'IFNG'),
event('Diabetes Mellitus',positive_correlation,'STREPTOZOCIN'),
event('STREPTOZOCIN',positive_correlation,'Diabetes Mellitus'),
event('CD4',negative_correlation,'TRAMETINIB'),
event('TRAMETINIB',negative_correlation,'CD4'),
event('IL31',negative_correlation,'IL4'),
event('IL4',negative_correlation,'IL31'),
event('NEOPLASMS',association,'IL31RA'),
event('CD4',negative_correlation,'NEOPLASMS'),
event('NEOPLASMS',negative_correlation,'CD4'),
event('NEOPLASMS',association,'IL4'),
event('IL31',negative_correlation,'CD4'),
event('CD4',negative_correlation,'IL31'),
event('IL31',negative_correlation,'NEOPLASMS'),
event('NEOPLASMS',negative_correlation,'IL31'),
event('IL31',negative_correlation,'GATA3'),
event('GATA3',negative_correlation,'IL31'),
event('IGH-V7183',association,'IL31'),
event('Breast Neoplasms',association,'IL31RA'),
event('NEOPLASMS',association,'IL2'),
event('Breast Neoplasms',association,'IL31'),
event('PSORIASIS',association,'JUN'),
event('Arthritis Psoriatic',association,'MALT1'),
event('MALT1',association,'GLS'),
event('IL17A',positive_correlation,'GLS'),
event('GLS',positive_correlation,'IL17A'),
event('JUN',association,'MALT1'),
event('HYPERPLASIA',association,'GLS'),
event('PSORIASIS',association,'MALT1'),
event('PSORIASIS',association,'IL17A'),
event('MALT1',association,'IL17A'),
event('JUN',association,'IL17A'),
event('JUN',association,'GLS'),
event('PSORIASIS',association,'GLS'),
event('HYPERPLASIA',association,'MALT1'),
event('COLITIS',positive_correlation,'IPILIMUMAB'),
event('IPILIMUMAB',positive_correlation,'COLITIS'),
event('Drug-Related Side Effects and Adverse Reactions',negative_correlation,'IPILIMUMAB'),
event('IPILIMUMAB',negative_correlation,'Drug-Related Side Effects and Adverse Reactions'),
event('Calcinosis Cutis',negative_correlation,'IPILIMUMAB'),
event('IPILIMUMAB',negative_correlation,'Calcinosis Cutis'),
event('Chemical and Drug Induced Liver Injury',positive_correlation,'IPILIMUMAB'),
event('IPILIMUMAB',positive_correlation,'Chemical and Drug Induced Liver Injury'),
event('MELANOMA',negative_correlation,'IPILIMUMAB'),
event('IPILIMUMAB',negative_correlation,'MELANOMA'),
event('MELANOMA',association,'TERT'),
event('IFNG',association,'TERT'),
event('CTLA4',association,'TERT'),
event('NEOPLASMS',association,'TERT'),
event('CD4',positive_correlation,'TERT'),
event('TERT',positive_correlation,'CD4'),
event('TGFB1',positive_correlation,'TERT'),
event('TERT',positive_correlation,'TGFB1'),
event('INFLAMMATION',association,'NFKB1'),
event('ATHEROSCLEROSIS',association,'NFKB1'),
event('KPNA4',association,'NFKB1'),
event('CTSD',association,'STAT1'),
event('LISTERIOSIS',association,'CTSD'),
event('LISTERIOSIS',association,'STAT1'),
event('LISTERIOSIS',association,'IL6'),
event('LISTERIOSIS',association,'IFNG'),
event('IL17A',positive_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',positive_correlation,'IL17A'),
event('STAT6',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'STAT6'),
event('SERPINB1-PS1',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'SERPINB1-PS1'),
event('IL13',association,'STAT6'),
event('IL17A',positive_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',positive_correlation,'IL17A'),
event('INFLAMMATION',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'INFLAMMATION'),
event('CCL11',negative_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',negative_correlation,'CCL11'),
event('EOSINOPHILIA',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'EOSINOPHILIA'),
event('IL13',negative_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',negative_correlation,'IL13'),
event('EOSINOPHILIA',negative_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',negative_correlation,'EOSINOPHILIA'),
event('Status Asthmaticus',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'Status Asthmaticus'),
event('CCL11',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'CCL11'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',association,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('SERPINB1-PS1',negative_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',negative_correlation,'SERPINB1-PS1'),
event('CLCA1',negative_correlation,'Polylactic Acid-Polyglycolic Acid Copolymer'),
event('Polylactic Acid-Polyglycolic Acid Copolymer',negative_correlation,'CLCA1'),
event('IL13',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'IL13'),
event('CLCA1',negative_correlation,'2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one'),
event('2-tert-butyl-9-fluoro-3 6-dihydro-7H-benz(h)imidazo(4 5-f)isoquinoline-7-one',negative_correlation,'CLCA1'),
event('IFNG',association,'JAK2'),
event('IL10',positive_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',positive_correlation,'IL10'),
event('STAT1',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'STAT1'),
event('JAK2',association,'STAT1'),
event('Inflammatory Bowel Diseases',association,'STAT1'),
event('Inflammatory Bowel Diseases',association,'IFNG'),
event('COLITIS',positive_correlation,'Trinitrobenzenesulfonic Acid'),
event('Trinitrobenzenesulfonic Acid',positive_correlation,'COLITIS'),
event('JAK2',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'JAK2'),
event('Trinitrobenzenesulfonic Acid',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'Trinitrobenzenesulfonic Acid'),
event('INFLAMMATION',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'INFLAMMATION'),
event('IFNG',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'IFNG'),
event('TGFB1',positive_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',positive_correlation,'TGFB1'),
event('Inflammatory Bowel Diseases',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'Inflammatory Bowel Diseases'),
event('TBX21',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'TBX21'),
event('IFNG',association,'STAT1'),
event('COLITIS',negative_correlation,'CIRSILINEOL'),
event('CIRSILINEOL',negative_correlation,'COLITIS'),
event('Crohn Disease',association,'STAT1'),
event('Crohn Disease',association,'IFNG'),
event('IFNG',association,'TBX21'),
event('Dextran Sulfate',association,'STAT1'),
event('SOCS1',negative_correlation,'COLITIS'),
event('COLITIS',negative_correlation,'SOCS1'),
event('Inflammatory Bowel Diseases',positive_correlation,'Dextran Sulfate'),
event('Dextran Sulfate',positive_correlation,'Inflammatory Bowel Diseases'),
event('IFNG',negative_correlation,'SOCS1'),
event('SOCS1',negative_correlation,'IFNG'),
event('Dextran Sulfate',association,'IFNG'),
event('FOXP3',positive_correlation,'SOCS1'),
event('SOCS1',positive_correlation,'FOXP3'),
event('FOXP3',negative_correlation,'Dextran Sulfate'),
event('Dextran Sulfate',negative_correlation,'FOXP3'),
event('SOCS1',negative_correlation,'Dextran Sulfate'),
event('Dextran Sulfate',negative_correlation,'SOCS1'),
event('SOCS1',positive_correlation,'CD4'),
event('CD4',positive_correlation,'SOCS1'),
event('COLITIS',positive_correlation,'Dextran Sulfate'),
event('Dextran Sulfate',positive_correlation,'COLITIS'),
event('STAT1',positive_correlation,'SOCS1'),
event('SOCS1',positive_correlation,'STAT1'),
event('COLITIS',association,'CD4'),
event('COLITIS',association,'STAT4'),
event('Bacterial Infections',association,'CD4'),
event('INFLAMMATION',association,'STAT4'),
event('IFNG',positive_correlation,'Bacterial Infections'),
event('Bacterial Infections',positive_correlation,'IFNG'),
event('Bacterial Infections',association,'TNF'),
event('STAT4',positive_correlation,'CD4'),
event('CD4',positive_correlation,'STAT4'),
event('Cytomegalovirus Infections',association,'STAT4'),
event('STAT4',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'STAT4'),
event('Carcinoma Hepatocellular',association,'IFNG'),
event('Carcinoma Hepatocellular',association,'IL4'),
event('IL10',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'IL10'),
event('TNF',positive_correlation,'IL10'),
event('IL10',positive_correlation,'TNF'),
event('Autoimmune Diseases',association,'IFNG'),
event('CD8A',positive_correlation,'TNF'),
event('TNF',positive_correlation,'CD8A'),
event('INFLAMMATION',association,'IFNG'),
event('CD8A',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'CD8A'),
event('PDCD1LG2',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'PDCD1LG2'),
event('PDCD1LG2',positive_correlation,'TNF'),
event('TNF',positive_correlation,'PDCD1LG2'),
event('INFLAMMATION',association,'TNF'),
event('CD4',positive_correlation,'PDCD1LG2'),
event('PDCD1LG2',positive_correlation,'CD4'),
event('CD4',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'CD4'),
event('Autoimmune Diseases',association,'TNF'),
event('CD8A',positive_correlation,'PDCD1LG2'),
event('PDCD1LG2',positive_correlation,'CD8A'),
event('INFLAMMATION',association,'PTPN2'),
event('PTPN2',association,'CD4'),
event('DYSBIOSIS',association,'PTPN2'),
event('Crohn Disease',association,'PTPN2'),
event('INFLAMMATION',association,'IL1B'),
event('NDUFA13',negative_correlation,'IL17A'),
event('IL17A',negative_correlation,'NDUFA13'),
event('Arthritis Experimental',association,'NDUFA13'),
event('IL6',association,'STAT3'),
event('NDUFA13',positive_correlation,'CD4'),
event('CD4',positive_correlation,'NDUFA13'),
event('INFLAMMATION',association,'IL6'),
event('NDUFA13',negative_correlation,'ARTHRITIS'),
event('ARTHRITIS',negative_correlation,'NDUFA13'),
event('IL17A',positive_correlation,'Arthritis Experimental'),
event('Arthritis Experimental',positive_correlation,'IL17A'),
event('TNFSF11',association,'NDUFA13'),
event('NDUFA13',positive_correlation,'IL2RA'),
event('IL2RA',positive_correlation,'NDUFA13'),
event('INFLAMMATION',association,'IL17A'),
event('NDUFA13',positive_correlation,'FOXP3'),
event('FOXP3',positive_correlation,'NDUFA13'),
event('STAT4',association,'TIMP1'),
event('STAT3',association,'TIMP1'),
event('Encephalomyelitis Autoimmune Experimental',association,'TIMP1'),
event('Autoimmune Diseases',association,'CD4'),
event('TNF',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'TNF'),
event('CD4',association,'IFNG'),
event('STAT1',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'STAT1'),
event('Chemical and Drug Induced Liver Injury',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'Chemical and Drug Induced Liver Injury'),
event('IFNG',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'IFNG'),
event('IL6',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'IL6'),
event('Hepatitis Autoimmune',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'Hepatitis Autoimmune'),
event('CD4',association,'STAT1'),
event('GPT',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'GPT'),
event('CD4',negative_correlation,'TIPIFARNIB'),
event('TIPIFARNIB',negative_correlation,'CD4'),
event('IL6',negative_correlation,'IL27'),
event('IL27',negative_correlation,'IL6'),
event('CXCL10',negative_correlation,'IL6'),
event('IL6',negative_correlation,'CXCL10'),
event('IL27',association,'IL27RA'),
event('IL6',association,'IL6ST'),
event('IL27',negative_correlation,'IL6'),
event('IL6',negative_correlation,'IL27'),
event('IL6ST',negative_correlation,'IL27'),
event('IL27',negative_correlation,'IL6ST'),
event('TNF',positive_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',positive_correlation,'TNF'),
event('IL6ST',association,'IL27'),
event('CXCL10',positive_correlation,'IL27'),
event('IL27',positive_correlation,'CXCL10'),
event('TLR4',positive_correlation,'IL27'),
event('IL27',positive_correlation,'TLR4'),
event('CXCL10',association,'IL27RA'),
event('IL27',association,'STAT3'),
event('CXCL10',association,'STAT3'),
event('INFLAMMATION',association,'IL27'),
event('IL27',negative_correlation,'LIPOPOLYSACCHARIDES'),
event('LIPOPOLYSACCHARIDES',negative_correlation,'IL27'),
event('TNF',negative_correlation,'IL27'),
event('IL27',negative_correlation,'TNF'),
event('IL4',association,'TGFB1'),
event('Inflammatory Bowel Diseases',negative_correlation,'MESALAMINE'),
event('MESALAMINE',negative_correlation,'Inflammatory Bowel Diseases'),
event('Colitis Ulcerative',negative_correlation,'TOFACITINIB'),
event('TOFACITINIB',negative_correlation,'Colitis Ulcerative'),
event('Colitis Ulcerative',negative_correlation,'MESALAMINE'),
event('MESALAMINE',negative_correlation,'Colitis Ulcerative'),
event('IL4',positive_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',positive_correlation,'IL4'),
event('CXCR3',association,'CD4'),
event('Drug Hypersensitivity',association,'IL5'),
event('Drug Hypersensitivity',association,'IL12B'),
event('CXCR6',negative_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',negative_correlation,'CXCR6'),
event('IFNG',positive_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',positive_correlation,'IFNG'),
event('IL10',positive_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',positive_correlation,'IL10'),
event('CXCR3',negative_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',negative_correlation,'CXCR3'),
event('TNF',positive_correlation,'Drug Hypersensitivity'),
event('Drug Hypersensitivity',positive_correlation,'TNF'),
event('Multiple Sclerosis',association,'CCR5'),
event('CCR5',association,'CD69'),
event('FAS',negative_correlation,'Multiple Sclerosis'),
event('Multiple Sclerosis',negative_correlation,'FAS'),
event('CD4',negative_correlation,'FAS'),
event('FAS',negative_correlation,'CD4'),
event('Multiple Sclerosis',association,'CD4'),
event('Multiple Sclerosis',association,'CD69'),
event('FAS',negative_correlation,'CCR5'),
event('CCR5',negative_correlation,'FAS'),
event('IL10',association,'CD4'),
event('IL4',association,'CD8A'),
event('THYMIDINE',association,'TRITIUM'),
event('CXCR4',association,'CD4'),
event('CCR5',association,'CD4'),
event('ITIH4',association,'CXCR4'),
event('CCR5',association,'ITIH4'),
event('INFECTIONS',association,'CXCR4'),
event('CXCR4',association,'CD8A'),
event('INFECTIONS',association,'CCR5'),
event('ITIH4',association,'CD4'),
event('ITIH4',association,'CD8A'),
event('Malaria Cerebral',association,'CCR5'),
event('Malaria Cerebral',association,'PRF1'),
event('BCL2',association,'NFKB1'),
event('MELANOMA',association,'BCL2'),
event('CCR5',association,'IL1RN'),
event('MELANOMA',association,'NFKB1'),
event('CASP3',association,'CCR5'),
event('CCR5',positive_correlation,'BAX'),
event('BAX',positive_correlation,'CCR5'),
event('MELANOMA',association,'RELA'),
event('CASP3',association,'NFKB1'),
event('BAX',association,'NFKB1'),
event('CCR5',positive_correlation,'BCL2'),
event('BCL2',positive_correlation,'CCR5'),
event('IL1RN',negative_correlation,'NEOPLASMS'),
event('NEOPLASMS',negative_correlation,'IL1RN'),
event('MELANOMA',association,'BIRC3'),
event('PARP1',association,'CCR5'),
event('NEOPLASMS',association,'NFKB1'),
event('RELA',positive_correlation,'CCR5'),
event('CCR5',positive_correlation,'RELA'),
event('MELANOMA',association,'BAX'),
event('MELANOMA',association,'IL1RN'),
event('CCR5',association,'NFKB1'),
event('MELANOMA',association,'CCR5'),
event('NEOPLASMS',association,'CCR5'),
event('PARP1',association,'NFKB1'),
event('MELANOMA',association,'CASP3'),
event('CCR5',positive_correlation,'BIRC3'),
event('BIRC3',positive_correlation,'CCR5'),
event('CD4',association,'CD8A'),
event('deoxyuridine triphosphate',association,'DNTT'),
event('CCR5',association,'CD8A'),
event('NEOPLASMS',negative_correlation,'MARAVIROC'),
event('MARAVIROC',negative_correlation,'NEOPLASMS'),
event('PDC',association,'CD8A'),
event('XCR1',association,'CD8A'),
event('INFECTIONS',association,'PDC'),
event('CCL5',association,'CCR5'),
event('Peripheral Nervous System Diseases',association,'CCL2'),
event('CD4',association,'CCL4'),
event('ITGAE',positive_correlation,'IL17A'),
event('IL17A',positive_correlation,'ITGAE'),
event('ITGAX',positive_correlation,'IL17A'),
event('IL17A',positive_correlation,'ITGAX'),
event('ITGAX',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'ITGAX'),
event('ITGAX',positive_correlation,'CD4'),
event('CD4',positive_correlation,'ITGAX'),
event('ITGAE',positive_correlation,'CD4'),
event('CD4',positive_correlation,'ITGAE'),
event('IFNG',association,'ITGAM'),
event('ITGAE',positive_correlation,'IFNG'),
event('IFNG',positive_correlation,'ITGAE'),
event('IL17A',association,'ITGAM'),
event('PCGF2',positive_correlation,'CXCR4'),
event('CXCR4',positive_correlation,'PCGF2'),
event('PCGF2',positive_correlation,'CCR9'),
event('CCR9',positive_correlation,'PCGF2'),
event('CD4',association,'CXCR4'),
event('PCGF2',positive_correlation,'CCL25'),
event('CCL25',positive_correlation,'PCGF2'),
event('PCGF2',positive_correlation,'CXCL12'),
event('CXCL12',positive_correlation,'PCGF2'),
event('CXCR4',negative_correlation,'TLR3'),
event('TLR3',negative_correlation,'CXCR4'),
event('NEOPLASMS',association,'TLR3'),
event('TLR3',negative_correlation,'Nasopharyngeal Carcinoma'),
event('Nasopharyngeal Carcinoma',negative_correlation,'TLR3'),
event('NEOPLASMS',association,'IFNA1'),
event('TLR3',negative_correlation,'Neoplasm Metastasis'),
event('Neoplasm Metastasis',negative_correlation,'TLR3'),
event('IFNA1',association,'TLR3'),
event('Nasopharyngeal Carcinoma',association,'CXCR4'),
event('CXCR4',association,'NFKB1'),
event('CXCR4',negative_correlation,'DEHYDROXYMETHYLEPOXYQUINOMICIN'),
event('DEHYDROXYMETHYLEPOXYQUINOMICIN',negative_correlation,'CXCR4'),
event('NFKB1',negative_correlation,'DEHYDROXYMETHYLEPOXYQUINOMICIN'),
event('DEHYDROXYMETHYLEPOXYQUINOMICIN',negative_correlation,'NFKB1'),
event('Anemia Aplastic',association,'NFKB1'),
event('CXCR4',positive_correlation,'CD4'),
event('CD4',positive_correlation,'CXCR4'),
event('Anemia Aplastic',association,'CXCR4'),
event('Anemia Aplastic',negative_correlation,'DEHYDROXYMETHYLEPOXYQUINOMICIN'),
event('DEHYDROXYMETHYLEPOXYQUINOMICIN',negative_correlation,'Anemia Aplastic'),
event('CXCR4',negative_correlation,'PLERIXAFOR'),
event('PLERIXAFOR',negative_correlation,'CXCR4'),
event('NEOPLASMS',association,'CXCR4'),
event('Kidney Neoplasms',negative_correlation,'AXITINIB'),
event('AXITINIB',negative_correlation,'Kidney Neoplasms'),
event('SIRT2',positive_correlation,'HYPERPLASIA'),
event('HYPERPLASIA',positive_correlation,'SIRT2'),
event('SIRT6',negative_correlation,'Epstein-Barr Virus Infections'),
event('Epstein-Barr Virus Infections',negative_correlation,'SIRT6'),
event('SIRT1',negative_correlation,'COVID-19'),
event('COVID-19',negative_correlation,'SIRT1'),
event('Colorectal Neoplasms',association,'SIRT4'),
event('Ventricular Remodeling',association,'SIRT3'),
event('COVID-19',association,'SIRT7'),
event('NEOPLASMS',association,'SIRT2'),
event('NEOPLASMS',association,'SIRT5'),
event('SIRT5',positive_correlation,'Colorectal Neoplasms'),
event('Colorectal Neoplasms',positive_correlation,'SIRT5'),
event('SIRT4',negative_correlation,'NEOPLASMS'),
event('NEOPLASMS',negative_correlation,'SIRT4'),
event('COVID-19',association,'SIRT4'),
event('Lupus Erythematosus Systemic',association,'SIRT1'),
event('NEOPLASMS',association,'SIRT7'),
event('INFLAMMATION',association,'SIRT1'),
event('Endometrial Neoplasms',association,'SIRT7'),
event('COVID-19',association,'SIRT6'),
event('SIRT6',negative_correlation,'Sarcoma Kaposi'),
event('Sarcoma Kaposi',negative_correlation,'SIRT6'),
event('NEOPLASMS',association,'SIRT1'),
event('COVID-19',association,'SIRT5'),
event('SIRT2',association,'IL4'),
event('COVID-19',association,'IL6'),
event('COVID-19',association,'IFNA2'),
event('Coronavirus Infections',association,'IFNG'),
event('IL1A',positive_correlation,'COVID-19'),
event('COVID-19',positive_correlation,'IL1A'),
event('CD4',negative_correlation,'COVID-19'),
event('COVID-19',negative_correlation,'CD4'),
event('IFNA2',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IFNA2'),
event('CCL2',positive_correlation,'COVID-19'),
event('COVID-19',positive_correlation,'CCL2'),
event('COVID-19',association,'IL10'),
event('CCL3',positive_correlation,'COVID-19'),
event('COVID-19',positive_correlation,'CCL3'),
event('IL1A',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL1A'),
event('IFNB1',positive_correlation,'COVID-19'),
event('COVID-19',positive_correlation,'IFNB1'),
event('IL7',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL7'),
event('COVID-19',association,'IL1B'),
event('CCL5',positive_correlation,'COVID-19'),
event('COVID-19',positive_correlation,'CCL5'),
event('IL1B',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL1B'),
event('IL10',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL10'),
event('IL6',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL6'),
event('CD8A',negative_correlation,'COVID-19'),
event('COVID-19',negative_correlation,'CD8A'),
event('IL23A',positive_correlation,'Coronavirus Infections'),
event('Coronavirus Infections',positive_correlation,'IL23A'),
event('CD247',association,'KLRK1'),
event('NEOPLASMS',association,'KLRK1'),
event('GLIOMA',association,'MICB'),
event('KLRK1',association,'MICB'),
event('KLRK1',association,'CD8A'),
event('GLIOMA',association,'KLRK1'),
event('GLIOMA',association,'MICA'),
event('MICA',association,'KLRK1'),
event('NEOPLASMS',association,'MICA'),
event('IFNG',positive_correlation,'KLRK1'),
event('KLRK1',positive_correlation,'IFNG'),
event('KLRK1',association,'CD4'),
event('CD28',negative_correlation,'CD8A'),
event('CD8A',negative_correlation,'CD28'),
event('Hepatitis B Chronic',association,'CD28'),
event('Chronic Disease',association,'CD8A'),
event('B3GAT1',association,'CD28'),
event('KLRK1',association,'CD28'),
event('Chronic Disease',association,'CD28'),
event('Hepatitis B Chronic',association,'B3GAT1'),
event('Hepatitis B Chronic',association,'TNF'),
event('Hepatitis B Chronic',association,'IFNG'),
event('CD28',negative_correlation,'IFNG'),
event('IFNG',negative_correlation,'CD28'),
event('Hepatitis B Chronic',association,'KLRK1'),
event('CD8A',positive_correlation,'GZMB'),
event('GZMB',positive_correlation,'CD8A'),
event('Hepatitis B Chronic',association,'CD8A'),
event('CD28',negative_correlation,'GZMB'),
event('GZMB',negative_correlation,'CD28'),
event('TNF',positive_correlation,'KLRK1'),
event('KLRK1',positive_correlation,'TNF'),
event('Hepatitis B Chronic',association,'CXCR3'),
event('Hepatitis B',association,'CD8A'),
event('CD28',negative_correlation,'TNF'),
event('TNF',negative_correlation,'CD28'),
event('Hepatitis B Chronic',association,'GZMB'),
event('Hepatitis B',association,'CD28'),
event('Hepatitis B Chronic',association,'CD4'),
event('NEOPLASMS',association,'MICB'),
event('KLRK1',bind,'MICB'),
event('MICB',association,'CD8A'),
event('Communicable Diseases',association,'MICB'),
event('Autoimmune Diseases',association,'MICB'),
event('SEC14L2',negative_correlation,'BNLF2A'),
event('BNLF2A',negative_correlation,'SEC14L2'),
event('Calcinosis Cutis',association,'CYP1B1'),
event('HYPOXIA',association,'CYP1B1'),
event('NEOPLASMS',association,'CYP1B1'),
event('Hereditary Breast and Ovarian Cancer Syndrome',association,'CDR2'),
event('Spinocerebellar Degenerations',association,'CDR2'),
event('NEOPLASMS',association,'CDR2'),
event('NEOPLASMS',association,'TP53'),
event('GLUTAMINE',association,'SEPHAROSE'),
event('CD8A',positive_correlation,'PROMUNE'),
event('PROMUNE',positive_correlation,'CD8A'),
event('CD8A',positive_correlation,'CPG-OLIGONUCLEOTIDE'),
event('CPG-OLIGONUCLEOTIDE',positive_correlation,'CD8A'),
event('PROMUNE',bind,'MLANA'),
event('MLANA',association,'CD8A'),
event('MELANOMA',negative_correlation,'PROMUNE'),
event('PROMUNE',negative_correlation,'MELANOMA'),
event('NEOPLASMS',negative_correlation,'PROMUNE'),
event('PROMUNE',negative_correlation,'NEOPLASMS'),
event('TNF',positive_correlation,'IL12B'),
event('IL12B',positive_correlation,'TNF'),
event('HIV Infections',association,'IFNG'),
event('Multiple Myeloma',association,'CD8A'),
event('Hodgkin Disease',association,'LMP-1'),
event('NEOPLASMS',association,'LMP-1'),
event('Nasopharyngeal Carcinoma',association,'PDLIM7'),
event('Nasopharyngeal Carcinoma',association,'LMP-1'),
event('Nasopharyngeal Carcinoma',association,'PSMB9'),
event('Epstein-Barr Virus Infections',association,'LMP-1'),
event('Hodgkin Disease',association,'PSMB9'),
event('Pancreatic Neoplasms',association,'CD8A'),
event('Neoplasms Squamous Cell',association,'CLCA2'),
event('NEOPLASMS',association,'CLCA2'),
event('GOITER',association,'TPO'),
event('CD8A',positive_correlation,'TPO'),
event('TPO',positive_correlation,'CD8A'),
event('CD8A',positive_correlation,'TG'),
event('TG',positive_correlation,'CD8A'),
event('Hashimoto Disease',association,'TPO'),
event('THYROIDITIS',association,'CD8A'),
event('GOITER',association,'TG'),
event('Hashimoto Disease',association,'TG'),
event('Hashimoto Disease',association,'CD8A'),
event('NEOPLASMS',association,'KLK3'),
event('Prostatic Neoplasms Castration-Resistant',association,'ACP3'),
event('Prostatic Neoplasms Castration-Resistant',association,'FOLH1'),
event('Prostatic Neoplasms Castration-Resistant',association,'IFNG'),
event('Prostatic Neoplasms Castration-Resistant',association,'KLK3'),
event('Diabetes Mellitus Type 1',association,'INS'),
event('PTPRN',association,'CD8A'),
event('Diabetes Mellitus',association,'G6PC2'),
event('Diabetes Mellitus',association,'CD8A'),
event('G6PC2',association,'CD8A'),
event('Diabetes Mellitus',association,'PTPRN'),
event('CD8A',positive_correlation,'GAD2'),
event('GAD2',positive_correlation,'CD8A'),
event('TRAV12-2',association,'CD8A'),
event('TRAJ60',association,'CD8A'),
event('Virus Diseases',association,'HLA-C'),
event('CD8B',positive_correlation,'ESR1'),
event('ESR1',positive_correlation,'CD8B'),
event('Breast Neoplasms',association,'ESR1'),
event('HLA-A',negative_correlation,'ESR1'),
event('ESR1',negative_correlation,'HLA-A'),
event('MRAP',association,'CD8A'),
event('DYNLT1',association,'CD8A'),
event('HIV Infections',association,'P.R69K'),
event('HIV Infections',association,'P.H87R'),
event('NEF',association,'CD8A'),
event('HIV Infections',association,'NEF'),
event('C.81A>G',association,'HIV Infections'),
event('Virus Diseases',association,'ERVK-20'),
event('INFECTIONS',association,'ERVK-20'),
event('ERVK-20',association,'MAMU-I'),
event('HIV Infections',association,'ERVK-20'),
event('NEF',association,'HLA-A'),
event('Rheumatic Diseases',association,'HLA-B'),
event('Spondylitis Ankylosing',association,'HLA-B'),
event('HAVCR2',association,'CD8A'),
event('GZMB',association,'HLA-B'),
event('HIV Infections',association,'HLA-B')
]).